### ISSUE TITLE
Is It possible to aggregate root?

### ISSUE THREAD

**Issue by artych** [Sigfried/supergroup#6]
It would be great to have `root` aggregation, same as for nodes. 
Now `root.aggregate(_.sum, 'charge')` seems doesn't work.
````javascript
    // this is awesome node aggregation
    sg = _.supergroup(data, ['patient', 'physician']);
    sg.aggregates(_.sum, 'charge'); // => [4220, 300, 600, 300, 3800, 400, 1260]
    sg[0].aggregate(_.sum, 'charge'); // => 4220

    // and it doesn't work with root
    root = sg.asRootVal('Total');
    root.aggregate(_.sum, 'charge'); // => return unexpected 0, expected 10880

**Comment by Sigfried** [comment]
I had an old version of supergroup.js in the gh-pages branch. I fixed that, which should fix this bug. I'm not sure where you're getting your example code from, but if it's from gh-pages examples, you might have capitalization of property names off (should be Patient instead of patient and stuff.)

Thanks for pointing out the problem! Let me know if it's not fixed for you.

**Comment by artych** [comment]
Yes, it works with master branch. The problem was that I've installed supergroup through bower and got 1.0.1 version.

**Comment by Sigfried** [comment]
Sorry about that! I updated it, so checking out from bower should be good to go.
